blueprint:
  name: Monitorar Sensor de Contato
  description: Monitora o estado de um sensor de contato e envia uma notificação para dois celulares específicos após um tempo configurável.
  domain: automation
  input:
    sensor_contato:
      name: Escolha o sensor de contato
      selector:
        entity:
          domain: binary_sensor
    tempo_espera:
      name: Tempo de espera (em minutos)
      description: Quantos minutos o sensor deve permanecer no estado configurado antes de disparar o evento.
      default: 15
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: min

trigger:
  - platform: state
    entity_id: !input sensor_contato
    to: "on"
    for:
      minutes: !input tempo_espera

actions:
  - action: notify.mobile_app_sm_s901e
    data:
      title: "Alerta: Sensor de Contato"
      message: "teste"
  - action: notify.mobile_app_iphone_de_jacqueline
    data:
      title: "Alerta: Sensor de Contato"
      message: "teste"

mode: single
