blueprint:
  name: Luz modo de dormir
  description: Liga uma luz no modo de dormir
  domain: script
  input:
    lampada:
      name: Lâmpada
      description: A lâmpada a ser controlada.
      selector:
        entity:
          domain: light
          multiple: false

sequence:
  - service: light.turn_on
    target:
      entity_id: !input lampada
    data:
      brightness_pct: 1
      color_temp: 450
