blueprint:
  name: Luz modo de dormir
  description: Liga uma luz no modo de dormir
  domain: script
  input:
    lampada:
      name: Lâmpada
      selector:
        entity:
          domain: light
trigger:
  - platform: time
    at: "22:00:00"
action:
  - service: light.turn_on
    target:
      entity_id: !input lampada
    data:
      brightness_pct: 1
      color_temp: 450
