blueprint:
  name: Paralelo Virtual com Alexa
  description: Acenda/Apaga todos os switchs/lights do grupo simultaneamente e executa uma rotina na Alexa
  domain: automation
  input:
    entrada_switchs:
      name: Escolha os pontos de Iluminação
      selector:
        entity:
          domain:
            - switch
            - light
          multiple: true
    alexa_device:
      name: Dispositivo Alexa
      description: Selecione o dispositivo Alexa para executar as rotinas
      selector:
        entity:
          domain: media_player
    rotina_on:
      name: Rotina para o estado ON
      description: Nome da rotina para quando os dispositivos forem ligados
      default: "sample_on"
    rotina_off:
      name: Rotina para o estado OFF
      description: Nome da rotina para quando os dispositivos forem desligados
      default: "sample_off"

trigger:
  platform: state
  entity_id: !input entrada_switchs

action:
  - service: >
      {% if trigger.to_state.state == "on" %}
        homeassistant.turn_on
      {% elif trigger.to_state.state == "off" %}
        homeassistant.turn_off
      {% endif %}
    target:
      entity_id: !input entrada_switchs

  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500

  - service: media_player.play_media
    data:
      media_content_type: routine
      media_content_id: >
        {% if trigger.to_state.state == "on" %}
          {{ rotina_on }}
        {% elif trigger.to_state.state == "off" %}
          {{ rotina_off }}
        {% endif %}
    target:
      entity_id: !input alexa_device

mode: single
