blueprint:
  name: Paralelo Virtual 3.0
  description: Acenda/Apaga todos os switchs/lights do grupo simultaneamente
  domain: automation
  input:
    entrada_switchs:
      name: Escolha os pontos de Iluminação
      selector:
        entity:
          domain:
            - switch
            - light
          multiple: true

trigger:
  platform: state
  entity_id: !input entrada_switchs

condition:
  - condition: template
    value_template: >
      {% set target_state = trigger.to_state.state %}
      {% for entity_id in (entrada_switchs | list) %}
        {% if states(entity_id) != target_state %}
          {% set execute_action = true %}
        {% endif %}
      {% endfor %}
      {{ execute_action is defined }}

action:
  - service: >
      {% if trigger.to_state.state == "on" %}
        homeassistant.turn_on
      {% elif trigger.to_state.state == "off" %}
        homeassistant.turn_off
      {% endif %}
    target:
      entity_id: !input entrada_switchs

mode: single
